### ISSUE TITLE
Databend benchmark is not valid the the latest Databend versions

### ISSUE THREAD

**Issue by zamazan4ik** [ClickHouse/ClickBench#113]
Current Databend benchmark implementation does not work since the latest Databend versions must spawn two processes: meta and query servers.

@PsiACE probably you are interested in this issue.

**Comment by PsiACE** [comment]
Databend has abandoned the embedded deployment method in the latest version. Databend v0.9.53 still supports continuing to use the embedded mode for deployment. We recommend deploying the meta service according to the documentation of the updated version.

**Comment by alexey-milovidov** [comment]
@PsiACE, let's update it according to the recommended method.
