### ISSUE TITLE
Why is the perf of cold scan  much worse than ever in the last commit of m5d.24xlarge. 

### ISSUE THREAD

**Issue by DengzhiLiu** [ClickHouse/ClickBench#118]
Who can tell me the changes between these two tests? Is there any change on the configuration, script or the Clickhouse binary?

https://github.com/ClickHouse/ClickBench/pull/89/commits/d3eee73e44d42001c1b35a32a8b7478b29236156#diff-ac79c887db3a7e002663efdc81b7b1d9856d54d4a0d968a1b72ce7b2f41d167f

![image](https://github.com/ClickHouse/ClickBench/assets/8384886/bfe45e24-89f9-422c-a63f-d76d37120fbc)

**Comment by nickitat** [comment]
it's hard to tell now. if you suspect that there was an error during measurement - pls rerun and submit updated results.
