### ISSUE TITLE
Doris vs Clickhouse for TPC-H

### ISSUE THREAD

**Issue by MacNale** [ClickHouse/ClickBench#144]
Came across this video.  https://youtu.be/w_hreEaiDQ4?si=WJzD4TY4U4KJSTfA&t=260

<img width="1597" alt="image" src="https://github.com/ClickHouse/ClickBench/assets/14235758/3676b149-0eb5-44ff-ad67-eaf2736f90ac">

Apparently Clickhouse is too slow compared to Doris as per the video. 

However clickbench shows comparable performance. One of these benchmark is right.. which one?

**Comment by alexey-milovidov** [comment]
Every benchmark is right and wrong in its own fashion.
You should evaluate performance on production scenarios rather than trusting benchmarks.

You can also collect a list of independent benchmarks and do a meta-analysis, like I do: https://github.com/ClickHouse/ClickHouse/issues/22398
