### ISSUE TITLE
Add Pandas

### ISSUE THREAD

**Issue by alexey-milovidov** [ClickHouse/ClickBench#207]
The scripts are here: https://x.com/auxten/status/1811101972952494517

**Comment by rschu1ze** [comment]
@auxten I agree it makes sense to add Pandas to ClickBench. Would you like to give this a try?

**Comment by auxten** [comment]
Yeah, I think I can give it a try. As most of the code is ready [here](https://colab.research.google.com/drive/1FogLujJ_-ds7RGurDrUnK-U0IW8a8Qd0).
But as pandas is not very memory efficient, there might be a lot of OOM.

**Comment by alexey-milovidov** [comment]
It's ok, we mark OOMs and failed queries as :skull_and_crossbones:

**Comment by alexey-milovidov** [comment]
Done.
