### ISSUE TITLE
Publish BigQuery benchmarks

### ISSUE THREAD

**Issue by buremba** [ClickHouse/ClickBench#218]
Hi!

It looks like BigQuery removed the DeWitt clause: https://cloud.google.com/terms/service-terms
Happy to add the results, let me know if I'm missing any details about the benchmarking limitations.

**Comment by rschu1ze** [comment]
If I am not mistaken, the service terms in the link you provided say this:

> 7. Benchmarking. Customer may conduct benchmark tests of the Services (each a "Test"). Customer may only publicly disclose the results of such Tests if (a) the public disclosure includes all necessary information to replicate the Tests, and (b) Customer allows Google to conduct benchmark tests of Customer's publicly available products or services and publicly disclose the results of such tests. Notwithstanding the foregoing, Customer may not do either of the following on behalf of a hyperscale public cloud provider without Google's prior written consent: (i) conduct (directly or through a third party) any Test or (ii) disclose the results of any such Test.

The wording is slightly different from the situation two years ago (I am looking at https://cube.dev/blog/dewitt-clause-or-can-you-benchmark-a-database) but the DeWitt clause is still in place as far as I understand.
