### ISSUE TITLE
DuckDB doesn't show up when Type = C++

### ISSUE THREAD

**Issue by devcrafter** [ClickHouse/ClickBench#26]
Type = `C++` only
<img width="916" alt="Screenshot 2022-09-07 at 12 46 57" src="https://user-images.githubusercontent.com/954088/188860263-d08f9fbe-c866-44b7-b863-71d916185db0.png">

The same filter by Type = `column-oriented`
<img width="904" alt="Screenshot 2022-09-07 at 12 47 39" src="https://user-images.githubusercontent.com/954088/188860504-57aa36b6-d84e-4010-9557-f8eb725394c0.png">

**Comment by alexey-milovidov** [comment]
Yes, my mistake - I tagged it as "C" by mistake.
I was thinking it has origins in MonetDB, but the friends from DuckDB explained to me that it is a completely new implementation.

**Comment by alexey-milovidov** [comment]
https://github.com/ClickHouse/ClickBench/commit/c1f4cb2dc934745a076c5cef848fb5c478c0dfda
