### ISSUE TITLE
Polars vs DataFusion benchmark results

### ISSUE THREAD

**Issue by rluvaton** [ClickHouse/ClickBench#264]
I would like to have polars vs data fusion results, but they have no common machine that I can compare with

What does it take to add it?

**Comment by rschu1ze** [comment]
You will need to set up an AWS EC2 machine with the desired instance type (see [here](https://aws.amazon.com/de/ec2/instance-types/)). During setup, go with the default.

Then clone the ClickBench repository and run polars/benchmark.sh resp. datafusion/benchmarks.sh.

**Comment by alexey-milovidov** [comment]
@rschu1ze, please see https://github.com/ClickHouse/ClickBench/pull/270#issuecomment-2543444463
