### ISSUE TITLE
Polars benchmark are very suboptimal.

### ISSUE THREAD

**Issue by ritchie46** [ClickHouse/ClickBench#268]
They benchmark the eager API which forces Polars to materialize every result and doesn't allow any optimizations. We state in our docs that if you benchmark Polars you should use the Lazy API. 

I also wonder why data must be loaded via Pandas?

I could take a stab at doing correct Polars queries. Does IO time need to be included or must queries load from DataFrames. I also wonder why pandas queries are mixed with the Polars queries file?

**Comment by rluvaton** [comment]
There should also be polars from parquet and sql like in datafusion and use [`polars-cli`](https://github.com/pola-rs/polars-cli) for that

**Comment by auxten** [comment]
@ritchie46 
For this patch, it is a test of 'Query on Dataframe'. As polars do not support query on dataframe directly, there is a load time.

You are welcomed to send a patch to correct usage of Polars😀

**Comment by ritchie46** [comment]
> As polars do not support query on dataframe directly, there is a load time.

I don't know what you mean? What do we not support?

**Comment by ritchie46** [comment]
> There should also be polars from parquet and sql like in datafusion and use [`polars-cli`](https://github.com/pola-rs/polars-cli) for that

We can write the queries from parquet. I can adapt the PR to do that. Our polars-cli is heavily outdated. I would recommend using Python Polars. That's our latest binary. We also can run SQL (but not everything as SQL is more an afterthought).

**Comment by auxten** [comment]
> > As polars do not support query on dataframe directly, there is a load time.
> 
> I don't know what you mean? What do we not support?

I mean for #222, it a "Query on Pandas Dataframe benchmark".
Forgive my ignorance, I don't know how Polars can query on a Pandas DataFrame directly without converting it to a Polars DataFrame.

**Comment by ritchie46** [comment]
It is not meant to query on pandas DataFrames. If pandas can query on it's own Dataframes, I think Polars should be able to do that as well.
