### ISSUE TITLE
Add result for Apache Doris

### ISSUE THREAD

**Issue by hello-stephen** [ClickHouse/ClickBench#28]
hi:
  I want to make a pr to add Apache Doris result, but I'm not sure about the Reproducibility. 
  It says 20 minutes. if I load data into Doris and wait for 5 minutes, then run query, is that OK?
  Doris still performs compaction in the backend when the load data is done, which affects the query performance.

**Comment by alexey-milovidov** [comment]
Let's collect both results:
- with waiting for compaction;
- without waiting.

And we will have both data points to compare.

Waiting for compaction will be somewhat unfair (for example, we don't do it for ClickHouse), but it's ok if it's clearly stated.

**Comment by hello-stephen** [comment]
OK，thanks.
