### ISSUE TITLE
Benchmark for StarRocks

### ISSUE THREAD

**Issue by mofeiatwork** [ClickHouse/ClickBench#3]
Hey there, I found that you got some problems when trying to benchmark StarRocks, and I'm willing to help, to make the benchmark result public.

Several ways to download StarRocks:
- [Official website](https://starrocks.com/try-starrocks-for-free-or-request-a-demo-starrocks?hsLang=en)
- [Github release](https://github.com/StarRocks/starrocks/releases) 

Current latest stable version is `2.2.2`, and latest RC version is `2.3.0-rc2`.

If you got any more problems when downloading or benchmarking, please contact our team at this issue or our slack channel.

**Comment by mofeiatwork** [comment]
I have submit a PR with detailed benchmark, please take a look: https://github.com/ClickHouse/ClickBench/pull/6

**Comment by alexey-milovidov** [comment]
Merged.
