### ISSUE TITLE
Q17 doesn't have sorting

### ISSUE THREAD

**Issue by mosinnik** [ClickHouse/ClickBench#33]
Q17 is Q16 but without sorting. So Q17 results always unpredictable. Should it be updated to use ORDER BY somehow?

Q17 Now is:
```
SELECT UserID, SearchPhrase, COUNT(*) FROM hits GROUP BY UserID, SearchPhrase LIMIT 10;
```

**Comment by alexey-milovidov** [comment]
This query was added this way in the original benchmark in 2013. Maybe we can change it, but it will require re-running all the results (around one week), most likely not worth doing. Non-determinism of the query result is not a big problem.

**Comment by mosinnik** [comment]
this query may have sense if this bench is "what people really can run to get stats". But Q29 is really strange even in comparison with this Q17. For Q29 better to rewrite to optimize but I think that is main idea. So if Q29 shouldn't be changed/tuned then Q17 should stay as is now.
