### ISSUE TITLE
Elasticsearch benchmarks flush the cache between queries

### ISSUE THREAD

**Issue by roborourke** [ClickHouse/ClickBench#41]
I've been trying to understand with my local benchmarking of roughly equivalent queries from my app (at least to get the data I need) why ES is outperforming CH by a factor of 10x in some cases, especially compared to the benchmarks here.

https://github.com/ClickHouse/ClickBench/blob/main/elasticsearch/run.sh#L11-L12

I can sort of see the reasoning for clearing the ES cache between queries but I feel that it's misleading with regards to the real world performance people will see.

While it's true from my observations that my equivalent CH and ES queries take around the same time from a cold start, ES quickly improves while CH stays relatively consistent and so on the whole much slower. ES also deals with concurrency much better, using Apache Benchmark with a concurrency of 3 I could see little change for ES but CH was taking up 4x longer than normal to deal with 1000 requests.

I feel at the very least there should be some indication that caches are not a factor in these benchmarks, and so should not be viewed as representative of real-world performance, at least in this case.

**Comment by tbragin** [comment]
I just followed instructions here: 
https://github.com/ClickHouse/ClickBench#caching

> Caching
> If the system contains a cache for query results, it should be disabled.
> 
> It is okay if the system performs caching for source data (buffer pools and similar). If the cache or buffer pools can be flushed, they should be flushed before the first run of every query.
> 
> If the system contains a cache for intermediate data, that cache should be disabled if it is located near the end of the query execution pipeline, thus similar to a query result cache.

**Comment by alexey-milovidov** [comment]
@roborourke let's add another result without flushing the cache. We can mark it "Elasticsearch (cache)".
It will be good for overall comparison.

**Comment by roborourke** [comment]
@tbragin sorry I missed that part of the methodology 🤦‍♂️  Thanks for pointing it out. I also misread the script I think, so it's just clearing the cache once for each query before running the query x times. That makes more sense.

@alexey-milovidov are you sure? It's ok if it doesn't fit with the overall methodology and you want to keep to that. Sorry I feel like I may be opening a can of worms here!

**Comment by tbragin** [comment]
The script flushes the cache inside the for loop, so that should be before every try. 

If someone has time to add an additional result with caching for ES, great! Perhaps, in the process, all results can also be updated with latest release of Elasticsearch that's come out since the time of initial publishing.

**Comment by alexey-milovidov** [comment]
> are you sure? It's ok if it doesn't fit with the overall methodology and you want to keep to that.

It's ok to add it to the repository - we have support for hiding some results by default.

**Comment by alexey-milovidov** [comment]
@roborourke, let's add additional results, it will be ok.
