### ISSUE TITLE
Clickhouse appears to run into an overflow on Q3

### ISSUE THREAD

**Issue by Mytherin** [ClickHouse/ClickBench#49]
Ran into this while adding result verification, the result produced by ClickHouse for Q3 appears to be incorrect - likely due to an internal overflow:

```sql
SELECT AVG(UserID) FROM hits;
┌─────────avg(UserID)─┐
│ -55945124888.916016 │
└─────────────────────┘
```

I'm not sure if this is intended behavior - it does not [appear to be listed on the documentation](https://clickhouse.com/docs/en/sql-reference/aggregate-functions/reference/avg/).

Adding a cast to `INT128` or `DOUBLE` fixes the problem:

```sql
SELECT AVG(toInt128(UserID)) FROM hits;
┌─avg(toInt128(UserID))─┐
│   2528953029789716000 │
└───────────────────────┘

SELECT AVG(CAST(UserID AS DOUBLE)) FROM hits;
┌─avg(CAST(UserID, 'DOUBLE'))─┐
│         2528953029789716000 │
└─────────────────────────────┘

```

**Comment by sundy-li** [comment]
Yes, it's by intended behavior. Duckdb use `hugeint_t` for aggregation `sum(int64_t)` yet ClickHouse use `UInt64` for `NearestFieldTypeImpl<UInt64>`.

**Comment by alexey-milovidov** [comment]
The docs has to be improved.
