### ISSUE TITLE
feat: add Github Actions to auto generate index.html

### ISSUE THREAD

**Issue by jychen7** [ClickHouse/ClickBench#98]
### Background

currently, after updating individual PR, we also need to manually run `generate-results.sh` to update `index.html`.

### Problem

1. It is inconvenient
2. It is confusing why PR on one system will "unexpectedly" update another system's result (e.g. [this Datafusion PR](https://github.com/ClickHouse/ClickBench/pull/97) updates Clickhouse result. I think because Clickhouse forgot to update `index.html` before)

### Proposal

add a GitHub action on the `main` branch to auto-generate `index.html` and push it back to the `main` branch
(be careful about the dead loop, we may prevent it by check git log whether `index.html` is modified)

**Comment by alexey-milovidov** [comment]
No objections. Please add a GitHub action.
